toml[build]
  publish = "public"
  functions = "netlify/functions"
```

**Guarda** (Ctrl + S)

---

## ✅ Tu Explorer debería quedar así:
```
FAKENEWS
├── netlify/           ← Ya lo tienes ✅
│   └── functions/
├── netlify.toml       ← El que vas a crear AHORA
└── public/            ← Ya lo tienes ✅
    ├── api/
    ├── app.js